package com.toy.model.generate;

import java.util.Date;

public class OrderEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_event.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_event.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_event.event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String event;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_event.occur_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date occurTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_event.operator
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String operator;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_event.id
	 * @return  the value of order_event.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_event.id
	 * @param id  the value for order_event.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_event.order_id
	 * @return  the value of order_event.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_event.order_id
	 * @param orderId  the value for order_event.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_event.event
	 * @return  the value of order_event.event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getEvent() {
		return event;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_event.event
	 * @param event  the value for order_event.event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setEvent(String event) {
		this.event = event;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_event.occur_time
	 * @return  the value of order_event.occur_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getOccurTime() {
		return occurTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_event.occur_time
	 * @param occurTime  the value for order_event.occur_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOccurTime(Date occurTime) {
		this.occurTime = occurTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_event.operator
	 * @return  the value of order_event.operator
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_event.operator
	 * @param operator  the value for order_event.operator
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}
}