package com.toy.model.generate;

public class OrderItemCommentImage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment_image.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment_image.comment_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String imageId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment_image.id
	 * @return  the value of order_item_comment_image.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment_image.id
	 * @param id  the value for order_item_comment_image.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment_image.comment_id
	 * @return  the value of order_item_comment_image.comment_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment_image.comment_id
	 * @param commentId  the value for order_item_comment_image.comment_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment_image.image_id
	 * @return  the value of order_item_comment_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getImageId() {
		return imageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment_image.image_id
	 * @param imageId  the value for order_item_comment_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setImageId(String imageId) {
		this.imageId = imageId;
	}
}