package com.toy.model.generate;

import java.util.Date;

public class OrderItemComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment.order_item_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String orderItemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment.rate
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment.comments
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String comments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_comment.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment.id
	 * @return  the value of order_item_comment.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment.id
	 * @param id  the value for order_item_comment.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment.order_item_id
	 * @return  the value of order_item_comment.order_item_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOrderItemId() {
		return orderItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment.order_item_id
	 * @param orderItemId  the value for order_item_comment.order_item_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOrderItemId(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment.rate
	 * @return  the value of order_item_comment.rate
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment.rate
	 * @param rate  the value for order_item_comment.rate
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setRate(String rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment.comments
	 * @return  the value of order_item_comment.comments
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment.comments
	 * @param comments  the value for order_item_comment.comments
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_comment.create_time
	 * @return  the value of order_item_comment.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_comment.create_time
	 * @param createTime  the value for order_item_comment.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}