package com.toy.model.generate;

public class ParternerOperater {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner_operater.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner_operater.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String parternerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner_operater.user_id
	 * @return  the value of parterner_operater.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner_operater.user_id
	 * @param userId  the value for parterner_operater.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner_operater.parterner_id
	 * @return  the value of parterner_operater.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getParternerId() {
		return parternerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner_operater.parterner_id
	 * @param parternerId  the value for parterner_operater.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setParternerId(String parternerId) {
		this.parternerId = parternerId;
	}
}