package com.toy.model.generate;

import java.util.Date;

public class Parterner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.linkman
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String linkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.telephone
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.mail
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parterner.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.id
	 * @return  the value of parterner.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.id
	 * @param id  the value for parterner.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.name
	 * @return  the value of parterner.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.name
	 * @param name  the value for parterner.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.desc
	 * @return  the value of parterner.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.desc
	 * @param desc  the value for parterner.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.linkman
	 * @return  the value of parterner.linkman
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.linkman
	 * @param linkman  the value for parterner.linkman
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.mobile
	 * @return  the value of parterner.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.mobile
	 * @param mobile  the value for parterner.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.telephone
	 * @return  the value of parterner.telephone
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.telephone
	 * @param telephone  the value for parterner.telephone
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.mail
	 * @return  the value of parterner.mail
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.mail
	 * @param mail  the value for parterner.mail
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.address
	 * @return  the value of parterner.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.address
	 * @param address  the value for parterner.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parterner.create_time
	 * @return  the value of parterner.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parterner.create_time
	 * @param createTime  the value for parterner.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}