package com.toy.model.generate;

import java.util.Date;

public class Receiptor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.is_default
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Boolean isDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receiptor.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.id
	 * @return  the value of receiptor.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.id
	 * @param id  the value for receiptor.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.user_id
	 * @return  the value of receiptor.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.user_id
	 * @param userId  the value for receiptor.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.name
	 * @return  the value of receiptor.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.name
	 * @param name  the value for receiptor.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.address
	 * @return  the value of receiptor.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.address
	 * @param address  the value for receiptor.address
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.mobile
	 * @return  the value of receiptor.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.mobile
	 * @param mobile  the value for receiptor.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.is_default
	 * @return  the value of receiptor.is_default
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.is_default
	 * @param isDefault  the value for receiptor.is_default
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receiptor.create_time
	 * @return  the value of receiptor.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receiptor.create_time
	 * @param createTime  the value for receiptor.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}