package com.toy.model.generate;

public class Tag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String category;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.id
	 * @return  the value of tag.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.id
	 * @param id  the value for tag.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.name
	 * @return  the value of tag.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.name
	 * @param name  the value for tag.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.category
	 * @return  the value of tag.category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.category
	 * @param category  the value for tag.category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCategory(String category) {
		this.category = category;
	}
}