package com.toy.model.generate;

import java.util.Date;

public class Task {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.user_id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.title
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.detail
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.priority
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.importance
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Integer importance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.state
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.duedate
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Date duedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.createtime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.closetime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	private Date closetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.id
	 * @return  the value of task.id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.id
	 * @param id  the value for task.id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.user_id
	 * @return  the value of task.user_id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.user_id
	 * @param userId  the value for task.user_id
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.title
	 * @return  the value of task.title
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.title
	 * @param title  the value for task.title
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.detail
	 * @return  the value of task.detail
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.detail
	 * @param detail  the value for task.detail
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.priority
	 * @return  the value of task.priority
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.priority
	 * @param priority  the value for task.priority
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.importance
	 * @return  the value of task.importance
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Integer getImportance() {
		return importance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.importance
	 * @param importance  the value for task.importance
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setImportance(Integer importance) {
		this.importance = importance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.state
	 * @return  the value of task.state
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.state
	 * @param state  the value for task.state
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.duedate
	 * @return  the value of task.duedate
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Date getDuedate() {
		return duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.duedate
	 * @param duedate  the value for task.duedate
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.createtime
	 * @return  the value of task.createtime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.createtime
	 * @param createtime  the value for task.createtime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.closetime
	 * @return  the value of task.closetime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public Date getClosetime() {
		return closetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.closetime
	 * @param closetime  the value for task.closetime
	 * @mbggenerated  Mon May 30 23:47:37 CST 2016
	 */
	public void setClosetime(Date closetime) {
		this.closetime = closetime;
	}
}