package com.toy.model.generate;

import java.util.Date;

public class Toy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String parternerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy.id
	 * @return  the value of toy.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy.id
	 * @param id  the value for toy.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy.parterner_id
	 * @return  the value of toy.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getParternerId() {
		return parternerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy.parterner_id
	 * @param parternerId  the value for toy.parterner_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setParternerId(String parternerId) {
		this.parternerId = parternerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy.name
	 * @return  the value of toy.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy.name
	 * @param name  the value for toy.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy.desc
	 * @return  the value of toy.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy.desc
	 * @param desc  the value for toy.desc
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy.create_time
	 * @return  the value of toy.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy.create_time
	 * @param createTime  the value for toy.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}