package com.toy.model.generate;

public class ToyCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_category.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_category.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_category.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String toyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_category.total_available
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Integer totalAvailable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_category.id
	 * @return  the value of toy_category.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_category.id
	 * @param id  the value for toy_category.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_category.name
	 * @return  the value of toy_category.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_category.name
	 * @param name  the value for toy_category.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_category.toy_id
	 * @return  the value of toy_category.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getToyId() {
		return toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_category.toy_id
	 * @param toyId  the value for toy_category.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setToyId(String toyId) {
		this.toyId = toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_category.total_available
	 * @return  the value of toy_category.total_available
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Integer getTotalAvailable() {
		return totalAvailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_category.total_available
	 * @param totalAvailable  the value for toy_category.total_available
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setTotalAvailable(Integer totalAvailable) {
		this.totalAvailable = totalAvailable;
	}
}