package com.toy.model.generate;

public class WeixinDrawback {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weixin_drawback.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weixin_drawback.drawback_bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String drawbackBillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weixin_drawback.weixin_drawbackcol
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String weixinDrawbackcol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weixin_drawback.id
	 * @return  the value of weixin_drawback.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weixin_drawback.id
	 * @param id  the value for weixin_drawback.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weixin_drawback.drawback_bill_id
	 * @return  the value of weixin_drawback.drawback_bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getDrawbackBillId() {
		return drawbackBillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weixin_drawback.drawback_bill_id
	 * @param drawbackBillId  the value for weixin_drawback.drawback_bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setDrawbackBillId(String drawbackBillId) {
		this.drawbackBillId = drawbackBillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weixin_drawback.weixin_drawbackcol
	 * @return  the value of weixin_drawback.weixin_drawbackcol
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getWeixinDrawbackcol() {
		return weixinDrawbackcol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weixin_drawback.weixin_drawbackcol
	 * @param weixinDrawbackcol  the value for weixin_drawback.weixin_drawbackcol
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setWeixinDrawbackcol(String weixinDrawbackcol) {
		this.weixinDrawbackcol = weixinDrawbackcol;
	}
}