package com.toy.model.generate;

public class Bill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Integer totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.payment_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String paymentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.id
	 * @return  the value of bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.id
	 * @param id  the value for bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.order_id
	 * @return  the value of bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.order_id
	 * @param orderId  the value for bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.total_amount
	 * @return  the value of bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Integer getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.total_amount
	 * @param totalAmount  the value for bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setTotalAmount(Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.payment_type
	 * @return  the value of bill.payment_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.payment_type
	 * @param paymentType  the value for bill.payment_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.state
	 * @return  the value of bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.state
	 * @param state  the value for bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}
}