package com.toy.model.generate;

public class Child extends ChildKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.age
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.gender
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String gender;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.name
	 * @return  the value of child.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.name
	 * @param name  the value for child.name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.age
	 * @return  the value of child.age
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.age
	 * @param age  the value for child.age
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.gender
	 * @return  the value of child.gender
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.gender
	 * @param gender  the value for child.gender
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}
}