package com.toy.model.generate;

public class ChildKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.child_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String childId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column child.user_user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.uid
	 * @return  the value of child.uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.uid
	 * @param uid  the value for child.uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.child_id
	 * @return  the value of child.child_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getChildId() {
		return childId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.child_id
	 * @param childId  the value for child.child_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setChildId(String childId) {
		this.childId = childId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column child.user_user_id
	 * @return  the value of child.user_user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserUserId() {
		return userUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column child.user_user_id
	 * @param userUserId  the value for child.user_user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserUserId(String userUserId) {
		this.userUserId = userUserId;
	}
}