package com.toy.model.generate;

public class DiscountItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount_item.bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount_item.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount_item.amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String resourceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount_item.id
	 * @return  the value of discount_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount_item.id
	 * @param id  the value for discount_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount_item.bill_id
	 * @return  the value of discount_item.bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount_item.bill_id
	 * @param billId  the value for discount_item.bill_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount_item.type
	 * @return  the value of discount_item.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount_item.type
	 * @param type  the value for discount_item.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount_item.amount
	 * @return  the value of discount_item.amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount_item.amount
	 * @param amount  the value for discount_item.amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setAmount(String amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount_item.resource_id
	 * @return  the value of discount_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount_item.resource_id
	 * @param resourceId  the value for discount_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}
}