package com.toy.model.generate;

public class DrawbackBill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column drawback_bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column drawback_bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column drawback_bill.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column drawback_bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Integer totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column drawback_bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column drawback_bill.id
	 * @return  the value of drawback_bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column drawback_bill.id
	 * @param id  the value for drawback_bill.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column drawback_bill.order_id
	 * @return  the value of drawback_bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column drawback_bill.order_id
	 * @param orderId  the value for drawback_bill.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column drawback_bill.type
	 * @return  the value of drawback_bill.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column drawback_bill.type
	 * @param type  the value for drawback_bill.type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column drawback_bill.total_amount
	 * @return  the value of drawback_bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Integer getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column drawback_bill.total_amount
	 * @param totalAmount  the value for drawback_bill.total_amount
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setTotalAmount(Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column drawback_bill.state
	 * @return  the value of drawback_bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column drawback_bill.state
	 * @param state  the value for drawback_bill.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}
}