package com.toy.model.generate;

import java.util.Date;

public class Gift {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.parterner_id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private String parternerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.name
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.desc
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.count
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.price
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.available
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private Boolean available;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift.create_time
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.id
	 * @return  the value of gift.id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.id
	 * @param id  the value for gift.id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.parterner_id
	 * @return  the value of gift.parterner_id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public String getParternerId() {
		return parternerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.parterner_id
	 * @param parternerId  the value for gift.parterner_id
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setParternerId(String parternerId) {
		this.parternerId = parternerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.name
	 * @return  the value of gift.name
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.name
	 * @param name  the value for gift.name
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.desc
	 * @return  the value of gift.desc
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.desc
	 * @param desc  the value for gift.desc
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.count
	 * @return  the value of gift.count
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.count
	 * @param count  the value for gift.count
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.price
	 * @return  the value of gift.price
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.price
	 * @param price  the value for gift.price
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.available
	 * @return  the value of gift.available
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public Boolean getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.available
	 * @param available  the value for gift.available
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setAvailable(Boolean available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift.create_time
	 * @return  the value of gift.create_time
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift.create_time
	 * @param createTime  the value for gift.create_time
	 * @mbggenerated  Thu Dec 17 23:07:56 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}