package com.toy.model.generate;

public class GiftImageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_image.image_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_image.gift_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    private String giftId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_image.image_id
     *
     * @return the value of gift_image.image_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_image.image_id
     *
     * @param imageId the value for gift_image.image_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    public void setImageId(String imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_image.gift_id
     *
     * @return the value of gift_image.gift_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    public String getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_image.gift_id
     *
     * @param giftId the value for gift_image.gift_id
     *
     * @mbggenerated Tue Feb 16 13:20:25 CST 2016
     */
    public void setGiftId(String giftId) {
        this.giftId = giftId;
    }
}