package com.toy.model.generate;

public class IdSequence {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column id_sequence.id
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	private Long id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column id_sequence.id
	 * @return  the value of id_sequence.id
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column id_sequence.id
	 * @param id  the value for id_sequence.id
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}
}