package com.toy.model.generate;

import java.util.Date;

public class Image {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.id
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.name
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.create_date
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.id
	 * @return  the value of image.id
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.id
	 * @param id  the value for image.id
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.name
	 * @return  the value of image.name
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.name
	 * @param name  the value for image.name
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.create_date
	 * @return  the value of image.create_date
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.create_date
	 * @param createDate  the value for image.create_date
	 * @mbggenerated  Tue Feb 16 13:20:25 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}