package com.toy.model.generate;

import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.receiptor_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String receiptorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.finish_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date finishTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.id
	 * @return  the value of order.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.id
	 * @param id  the value for order.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.user_id
	 * @return  the value of order.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.user_id
	 * @param userId  the value for order.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.state
	 * @return  the value of order.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.state
	 * @param state  the value for order.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.receiptor_id
	 * @return  the value of order.receiptor_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getReceiptorId() {
		return receiptorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.receiptor_id
	 * @param receiptorId  the value for order.receiptor_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setReceiptorId(String receiptorId) {
		this.receiptorId = receiptorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.create_time
	 * @return  the value of order.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.create_time
	 * @param createTime  the value for order.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.finish_time
	 * @return  the value of order.finish_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.finish_time
	 * @param finishTime  the value for order.finish_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}
}