package com.toy.model.generate;

public class OrderItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.item_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String itemType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String resourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.count
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Integer count;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.id
	 * @return  the value of order_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.id
	 * @param id  the value for order_item.id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.order_id
	 * @return  the value of order_item.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.order_id
	 * @param orderId  the value for order_item.order_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.item_type
	 * @return  the value of order_item.item_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getItemType() {
		return itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.item_type
	 * @param itemType  the value for order_item.item_type
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.resource_id
	 * @return  the value of order_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.resource_id
	 * @param resourceId  the value for order_item.resource_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.count
	 * @return  the value of order_item.count
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.count
	 * @param count  the value for order_item.count
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCount(Integer count) {
		this.count = count;
	}
}