package com.toy.model.generate;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
	 * @return  the value of role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
	 * @param roleName  the value for role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}