package com.toy.model.generate;

import java.util.Date;

public class Survey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.parterner_id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String parternerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.name
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.description
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.point
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.category
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.state
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.create_time
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.id
     *
     * @return the value of survey.id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.id
     *
     * @param id the value for survey.id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.parterner_id
     *
     * @return the value of survey.parterner_id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getParternerId() {
        return parternerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.parterner_id
     *
     * @param parternerId the value for survey.parterner_id
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setParternerId(String parternerId) {
        this.parternerId = parternerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.name
     *
     * @return the value of survey.name
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.name
     *
     * @param name the value for survey.name
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.description
     *
     * @return the value of survey.description
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.description
     *
     * @param description the value for survey.description
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.point
     *
     * @return the value of survey.point
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.point
     *
     * @param point the value for survey.point
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.category
     *
     * @return the value of survey.category
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.category
     *
     * @param category the value for survey.category
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.state
     *
     * @return the value of survey.state
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.state
     *
     * @param state the value for survey.state
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.create_time
     *
     * @return the value of survey.create_time
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.create_time
     *
     * @param createTime the value for survey.create_time
     *
     * @mbggenerated Thu Feb 18 09:02:10 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}