package com.toy.model.generate;

public class ToyImageKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_image.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String toyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String imageId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_image.toy_id
	 * @return  the value of toy_image.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getToyId() {
		return toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_image.toy_id
	 * @param toyId  the value for toy_image.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setToyId(String toyId) {
		this.toyId = toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_image.image_id
	 * @return  the value of toy_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getImageId() {
		return imageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_image.image_id
	 * @param imageId  the value for toy_image.image_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setImageId(String imageId) {
		this.imageId = imageId;
	}
}