package com.toy.model.generate;

public class ToyTagKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_tag.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String toyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column toy_tag.tag_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String tagId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_tag.toy_id
	 * @return  the value of toy_tag.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getToyId() {
		return toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_tag.toy_id
	 * @param toyId  the value for toy_tag.toy_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setToyId(String toyId) {
		this.toyId = toyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column toy_tag.tag_id
	 * @return  the value of toy_tag.tag_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column toy_tag.tag_id
	 * @param tagId  the value for toy_tag.tag_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setTagId(String tagId) {
		this.tagId = tagId;
	}
}