package com.toy.model.generate;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.salt
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.salt
	 * @return  the value of user.salt
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.salt
	 * @param salt  the value for user.salt
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
	 * @return  the value of user.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
	 * @param mobile  the value for user.mobile
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.state
	 * @return  the value of user.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.state
	 * @param state  the value for user.state
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}