package com.toy.model.generate;

public class UserCoin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin.user_id
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin.count
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin.user_id
     *
     * @return the value of user_coin.user_id
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin.user_id
     *
     * @param userId the value for user_coin.user_id
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin.count
     *
     * @return the value of user_coin.count
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin.count
     *
     * @param count the value for user_coin.count
     *
     * @mbggenerated Wed Dec 16 22:26:23 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}