package com.toy.model.generate;

public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.role_name
	 * @return  the value of user_role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.role_name
	 * @param roleName  the value for user_role.role_name
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.user_id
	 * @return  the value of user_role.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.user_id
	 * @param userId  the value for user_role.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}