package com.toy.model.generate;

public class WeixinCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weixin_customer.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weixin_customer.wx_uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	private String wxUid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weixin_customer.user_id
	 * @return  the value of weixin_customer.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weixin_customer.user_id
	 * @param userId  the value for weixin_customer.user_id
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weixin_customer.wx_uid
	 * @return  the value of weixin_customer.wx_uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public String getWxUid() {
		return wxUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weixin_customer.wx_uid
	 * @param wxUid  the value for weixin_customer.wx_uid
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	public void setWxUid(String wxUid) {
		this.wxUid = wxUid;
	}
}