package com.toy.data.generate;

import com.toy.model.generate.BillingItem;
import com.toy.model.generate.BillingItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillingItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(BillingItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(BillingItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(BillingItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(BillingItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<BillingItem> selectByExample(BillingItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	BillingItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BillingItem record, @Param("example") BillingItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") BillingItem record, @Param("example") BillingItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(BillingItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billing_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(BillingItem record);
}