package com.toy.data.generate;

import com.toy.model.generate.Bill;
import com.toy.model.generate.BillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<Bill> selectByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	Bill selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Bill record, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") Bill record, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(Bill record);
}