package com.toy.data.generate;

import com.toy.model.generate.DrawbackBill;
import com.toy.model.generate.DrawbackBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawbackBillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(DrawbackBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(DrawbackBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(DrawbackBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(DrawbackBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<DrawbackBill> selectByExample(DrawbackBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	DrawbackBill selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DrawbackBill record, @Param("example") DrawbackBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") DrawbackBill record, @Param("example") DrawbackBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(DrawbackBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drawback_bill
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(DrawbackBill record);
}