package com.toy.data.generate;

import com.toy.model.generate.IdSequence;
import com.toy.model.generate.IdSequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdSequenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int countByExample(IdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int deleteByExample(IdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int insert(IdSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int insertSelective(IdSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	List<IdSequence> selectByExample(IdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int updateByExampleSelective(@Param("record") IdSequence record, @Param("example") IdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table id_sequence
	 * @mbggenerated  Wed Dec 09 22:29:14 CST 2015
	 */
	int updateByExample(@Param("record") IdSequence record, @Param("example") IdSequenceExample example);
}