package com.toy.data.generate;

import com.toy.model.generate.OrderItemComment;
import com.toy.model.generate.OrderItemCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(OrderItemCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(OrderItemCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(OrderItemComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(OrderItemComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<OrderItemComment> selectByExample(OrderItemCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	OrderItemComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") OrderItemComment record,
			@Param("example") OrderItemCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") OrderItemComment record, @Param("example") OrderItemCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(OrderItemComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_comment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(OrderItemComment record);
}