package com.toy.data.generate;

import com.toy.model.generate.ToyImageExample;
import com.toy.model.generate.ToyImageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ToyImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ToyImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(ToyImageKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(ToyImageKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(ToyImageKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<ToyImageKey> selectByExample(ToyImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ToyImageKey record, @Param("example") ToyImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_image
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") ToyImageKey record, @Param("example") ToyImageExample example);
}