package com.toy.data.generate;

import com.toy.model.generate.Toy;
import com.toy.model.generate.ToyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ToyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ToyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(Toy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(Toy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<Toy> selectByExample(ToyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	Toy selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Toy record, @Param("example") ToyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") Toy record, @Param("example") ToyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(Toy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(Toy record);
}