package com.toy.data.generate;

import com.toy.model.generate.ToyTagExample;
import com.toy.model.generate.ToyTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ToyTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ToyTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(ToyTagKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(ToyTagKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(ToyTagKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<ToyTagKey> selectByExample(ToyTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ToyTagKey record, @Param("example") ToyTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_tag
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") ToyTagKey record, @Param("example") ToyTagExample example);
}