package com.toy.data.generate;

import com.toy.model.generate.WeixinDrawback;
import com.toy.model.generate.WeixinDrawbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinDrawbackMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(WeixinDrawbackExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(WeixinDrawbackExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(WeixinDrawback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(WeixinDrawback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<WeixinDrawback> selectByExample(WeixinDrawbackExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	WeixinDrawback selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") WeixinDrawback record,
			@Param("example") WeixinDrawbackExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") WeixinDrawback record, @Param("example") WeixinDrawbackExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(WeixinDrawback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_drawback
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(WeixinDrawback record);
}