package com.toy.data.generate;

import com.toy.model.generate.Child;
import com.toy.model.generate.ChildExample;
import com.toy.model.generate.ChildKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChildMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(ChildKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(Child record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(Child record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<Child> selectByExample(ChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	Child selectByPrimaryKey(ChildKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Child record, @Param("example") ChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") Child record, @Param("example") ChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(Child record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table child
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(Child record);
}