package com.toy.data.generate;

import com.toy.model.generate.OrderEvent;
import com.toy.model.generate.OrderEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderEventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(OrderEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(OrderEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(OrderEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(OrderEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<OrderEvent> selectByExample(OrderEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	OrderEvent selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") OrderEvent record, @Param("example") OrderEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") OrderEvent record, @Param("example") OrderEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(OrderEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_event
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(OrderEvent record);
}