package com.toy.data.generate;

import com.toy.model.generate.OrderItem;
import com.toy.model.generate.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<OrderItem> selectByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	OrderItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(OrderItem record);
}