package com.toy.data.generate;

import com.toy.model.generate.Parterner;
import com.toy.model.generate.ParternerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParternerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ParternerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ParternerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(Parterner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(Parterner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<Parterner> selectByExample(ParternerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	Parterner selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Parterner record, @Param("example") ParternerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") Parterner record, @Param("example") ParternerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(Parterner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(Parterner record);
}