package com.toy.data.generate;

import com.toy.model.generate.ParternerOperater;
import com.toy.model.generate.ParternerOperaterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParternerOperaterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ParternerOperaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ParternerOperaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(ParternerOperater record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(ParternerOperater record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<ParternerOperater> selectByExample(ParternerOperaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	ParternerOperater selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ParternerOperater record,
			@Param("example") ParternerOperaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") ParternerOperater record, @Param("example") ParternerOperaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(ParternerOperater record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parterner_operater
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(ParternerOperater record);
}