package com.toy.data.generate;

import com.toy.model.generate.Receiptor;
import com.toy.model.generate.ReceiptorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceiptorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ReceiptorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ReceiptorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(Receiptor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(Receiptor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<Receiptor> selectByExample(ReceiptorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	Receiptor selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Receiptor record, @Param("example") ReceiptorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") Receiptor record, @Param("example") ReceiptorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(Receiptor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receiptor
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(Receiptor record);
}