package com.toy.data.generate;

import com.toy.model.generate.ToyCategory;
import com.toy.model.generate.ToyCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(ToyCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(ToyCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(ToyCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(ToyCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<ToyCategory> selectByExample(ToyCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	ToyCategory selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ToyCategory record, @Param("example") ToyCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") ToyCategory record, @Param("example") ToyCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(ToyCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table toy_category
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(ToyCategory record);
}