package com.toy.data.generate;

import com.toy.model.generate.WeixinPayment;
import com.toy.model.generate.WeixinPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinPaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(WeixinPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(WeixinPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(WeixinPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(WeixinPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<WeixinPayment> selectByExample(WeixinPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	WeixinPayment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") WeixinPayment record, @Param("example") WeixinPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") WeixinPayment record, @Param("example") WeixinPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(WeixinPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_payment
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(WeixinPayment record);
}