package com.toy.data.generate;

import com.toy.model.generate.WeixinCustomer;
import com.toy.model.generate.WeixinCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinCustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int countByExample(WeixinCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByExample(WeixinCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insert(WeixinCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int insertSelective(WeixinCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	List<WeixinCustomer> selectByExample(WeixinCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	WeixinCustomer selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") WeixinCustomer record,
			@Param("example") WeixinCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByExample(@Param("record") WeixinCustomer record, @Param("example") WeixinCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKeySelective(WeixinCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weixin_customer
	 * @mbggenerated  Mon Dec 07 22:17:15 CST 2015
	 */
	int updateByPrimaryKey(WeixinCustomer record);
}